### ISSUE TITLE
Allow Configuration of W vs Kw for energy sensors

### ISSUE THREAD

**Issue by gpshml** [CJNE/ha-myenergi#369]
I have inverter settings which are in Kw and for ease of display on dashboards it is neater to show #.#Kw.

It would be great if we could select Kw or W, or allow the HA UI to change it as it does with other sensors.

I could duplicate the sensors and change the measure which I will do but not sure why the integration does not allow it to change..

Great integration BTW, thank you.

**Comment by LeiChat** [comment]
I am keen to learn more about Integration development too. 

Might be related to the sensor device class?

Energy / Power?

https://developers.home-assistant.io/docs/core/entity/sensor?_highlight=units&_highlight=kw#available-device-classes

**Comment by LeiChat** [comment]
I have observed the same... any ideas why?

Could the options be specified as an array?

I found a thread on community.home-assistant.io that mentions POWER_KILO_WATT

![image](https://user-images.githubusercontent.com/23559551/235938643-8eaf0a88-e8a5-4ae8-b392-d5ad6715b9e0.png)

**Comment by LeiChat** [comment]
Had a look at GivEnergy integration this morning and noticed reference to a `native_unit_of_measurement`.
Might that perhaps define the sensor's value without preventing it from being converted?

![image](https://user-images.githubusercontent.com/23559551/236128983-68ebc298-d155-4629-879a-b8405ab30421.png)

**Comment by G6EJD** [comment]
Obviously it won’t change the value just the units used for interpretation, so if the value is in Watts say 100W and the units are changed to eg kW then the result will be 100kW

**Comment by LeiChat** [comment]
@gpshml Are you able to amend the title of the issue to "power sensors" rather than "energy sensors", please?
Each time I get a notification I forget we've already covered the power vs energy unit thing.

**Comment by jwillemsen** [comment]
Native unit should solve this, when the user selects a different unit in the UI then HA will do a conversion

**Comment by G6EJD** [comment]
The original issue is confused with units, if energy then it has to include time and anyway there are already power entities, so this issue should be closed.

**Comment by x4N70pHyLL** [comment]
> Native unit should solve this, when the user selects a different unit in the UI then HA will do a conversion

I second this and would appreciate if it will be corrected, I think the issue is valid.

When clicking here, it should take effect and currently it doesn't.

<img width="551" alt="Image" src="https://github.com/user-attachments/assets/b4955318-0755-4245-a64d-72b3626c8bbe" />

As zappi is handling significant power levels, the usual unit is more kW than W, so it should be at least changeable by the user

**Comment by x4N70pHyLL** [comment]
The issue still persists on the W / kW entities, I still can change the unit like shown in my screenshot above but there is no effect.

Would appreciate if you reopen the issue

**Comment by G6EJD** [comment]
OK, but I tried this on my HA and it works perfectly.

So lets check what versions do you use.
This integration: 0.0.30
Home Assistant: 2025.7

**Comment by AJediIAm** [comment]
> The issue still persists on the W / kW entities, I still can change the unit like shown in my screenshot above but there is no effect.
> 
> Would appreciate if you reopen the issue

Can you share a screenshot?
I'm not able to reproduce the issue myself. Let's compare notes and see if we can find the differences.

**Comment by x4N70pHyLL** [comment]
> > The issue still persists on the W / kW entities, I still can change the unit like shown in my screenshot above but there is no effect.
> > Would appreciate if you reopen the issue
> 
> Can you share a screenshot? I'm not able to reproduce the issue myself. Let's compare notes and see if we can find the differences.

Please see my screenshot in [this](https://github.com/CJNE/ha-myenergi/issues/369#issuecomment-2757175438) post. It still is the same behavior, nothing changed.

**Comment by G6EJD** [comment]
Thinking this issue through, it's a change made to an entity, and further looking through this integration, it does not manipulate entities.

You really need to confirm the Home Assistant version and Integration version.

Looking back at the HA versions, changing units was an issue that has been resolved.

Both Jaap's and my HA variants do-not show this behaviour.

So we need to start from the basics.

**Comment by LeiChat** [comment]
An example for another integration and how it impacts the dashboard 'entity' card.

![Image](https://github.com/user-attachments/assets/d22dfbed-17b9-4d58-8363-1a36bf9f2ca1)

![Image](https://github.com/user-attachments/assets/3ecada1f-f7d2-490b-91fb-ff91f76da84d)

**Comment by G6EJD** [comment]
I have been reviewing the construction of entities, and cannot see any issues:

  "unit": UnitOfPower.WATT,

Is the default unit, which is correct. Graphs are displayed in WATTS

If I change the default to KILO_WATT, then the units change and graphs are displayed in kW

**I can confirm that units are not changing for MyEnergi entities, but they do for other integrations.**

There are no recent HA notes on this topic/issue, other than similar issues were fixed in 2022, and the topic was closed.

Using SHELLY's integration as a reference, where I can change units to any chosen type and values are converted, displayed and graphed correctly, then this is suggests the way that Entities are created is the cause of the issue.

I cannot find the contents of 'from homeassistant.const import UnitOfPower' to confirm the correct unit definitions are selected, but they appear to be.

In the function:
def create_power_meta(name, prop_name, category=None):
    return {
        "name": name,
        "prop_name": prop_name,
        "device_class": SensorDeviceClass.POWER,
        "unit": UnitOfPower.WATT,
        "category": category,
        "icon": "mdi:flash",
        "state_class": SensorStateClass.MEASUREMENT,
        "attrs": {},
    }

Explicitly defining the unit gives the same answer, so I answered the UnitOfPower.WATT query.

At the moment I cannot find any method of Entity creation that would change the behaviour  in HA, but clearly there is a method that needs to be applied, but what?

@CJNE Johan, any ideas please.

**Comment by LeiChat** [comment]
I'm still learning Python, but I think it might be these two functions where 'native_unit_of_measurement' would need adding:

![Image](https://github.com/user-attachments/assets/514707f7-d0f4-4c73-8a6a-280c604e9d0a)

**Comment by LeiChat** [comment]
Scratch that. Tested in in my HA (edited local sensors.py, checked config and restarted) and I'm still not able to amend the unit in the UI for the myenergi power sensors.

**Comment by x4N70pHyLL** [comment]
> Thinking this issue through, it's a change made to an entity, and further looking through this integration, it does not manipulate entities.
> 
> You really need to confirm the Home Assistant version and Integration version.
> 
> Looking back at the HA versions, changing units was an issue that has been resolved.
> 
> Both Jaap's and my HA variants do-not show this behaviour.
> 
> So we need to start from the basics.

For the sake of completeness (I guess you got all the info from @LeiChat already): I am using HA 2025.7.0 but the issue persists since the first time I discovered it, so around 2024-11 probably. I am normally at max one/two versions behind latest.

And I am trying to change from Watt to Kilowatt.

**Comment by CJNE** [comment]
I haven't come around do test this myself but i think the correct approach is to add the native_unit_of_measurement property, i believe this will allow you to make customized units in HA. @LeiChat looking at what you tried, it seems like you tried to use a power unit for an energy sensor, that might explain why it didn't work?
Energy meter sensors should use kWh and power sensors should use W, as native units.

**Comment by G6EJD** [comment]
I did add the native unit to test the effect and it halted all power entity reporting. I struggled with the parameter "unit" as it was t clear to me if this was what I call a logical parameter name or an actual value name but in the documentation I didn't find "unit" if that makes sense. So is it simply replacing "unit"
with
"native_unit_of_measurement" then followed by the correct WATT unit. And similarly for energy functions.

**Comment by G6EJD** [comment]
Replacing "unit" with "native_unit_of_measurement" stops all associated sensors from operating/become unavailable.

I have tried many solutions and none yet found, so I'm going back to look through the Shelly version to see if there is a subtle difference.

**Comment by LeiChat** [comment]
Sharing a snippet from another HACS integration, three properties it's setting for a power sensor:
```
    _attr_state_class = SensorStateClass.MEASUREMENT
    _attr_entity_category = EntityCategory.DIAGNOSTIC
    _attr_native_unit_of_measurement = UnitOfPower.WATT
```

**Comment by G6EJD** [comment]
I've followed through the process of creating entities and adding unit attributes, and I cannot see anything that deviates from the process, so I'm drawing a blank for now. As I have Shelly devices, I'm going to explore their python structure to see what the differences are.
